### ISSUE TITLE
建议添加信息

### ISSUE THREAD

**Issue by yfdyh000** [jingyu9575/select-after-closing-current#1]
1. AMO上添加用户支持信息-网站 到Github issue，您的各项目。
2. 父标签页尚未支持。
3. 或许应为项目建立README，至少回链到AMO页面（可以用 https://shields.io/ 上的徽标）。

**Comment by jingyu9575** [comment]
已添加。
父标签页选项在最新的 Nightly (2017-09-21) 中是支持的。[Bug 1238314](https://bugzilla.mozilla.org/show_bug.cgi?id=1238314) RESOLVED FIXED in Firefox 57。
