### ISSUE TITLE
Lag before kicking in / switches to Firefox default order tab before it gets pulled to custom order tab

### ISSUE THREAD

**Issue by corobin** [jingyu9575/select-after-closing-current#10]
When closing a tab, the next selected tab is very briefly the tab that would be the Firefox default, before Select After Closing Current kicks in and switches the tab to the one that would be selected by custom ordering.

For example, if the Firefox default is to go to tab on the right, and the custom order is to go to tab on the left, and we are currently focused on the middle of three tabs, what would happen is that after closing the current tab it'll briefly flash the tab on the right before being focused back to the tab on the left.

The problem that this causes: when Firefox is set to pause all auto-play of background tabs until a tab is selected, this very brief period where the wrong tab is selected is enough to make the media auto-play.

So in our previous example, if the right tab is a youtube video that I opened into the background, it's paused. But after I close the current (middle) tab it'll switch briefly to the right tab and cause the video to start playing, and a blink after that switch to the left tab as I have configured, but now the tab on the right is playing in the background.

This feels like a problem with the new Quantum APIs, is this fixable?  Thanks!

**Comment by jingyu9575** [comment]
This is a problem with the Quantum APIs, and I do not think this is fixable in the current Firefox. Firefox 57+ (Quantum) compatible extensions cannot access Firefox's internal working, so the browser's default selection cannot be prevented. This extension can only fix it afterwards. In addition to media auto-play, this also interferes with tab discarding (#9).

See these related feature requests in Firefox's bug tracker: [1419947](https://bugzilla.mozilla.org/show_bug.cgi?id=1419947), [1422509](https://bugzilla.mozilla.org/show_bug.cgi?id=1422509), [1459402 (tracking)](https://bugzilla.mozilla.org/show_bug.cgi?id=1459402), [1419649](https://bugzilla.mozilla.org/show_bug.cgi?id=1419649).

**Comment by asmwarrior** [comment]
I also see this annoying behaviour, unluckily, this is not fixed yet, I hope FireFox will fix this issue soon. Anyway, thanks for the great add-on.

BTW, I think you should state this issue on your add-on page, such as adding an "known issue section".

**Comment by jo-so** [comment]
Is it technically possible to intercept the close event, jump to the preferred “next tab after close”, jump back and let the close event focus the last active tab?

**Comment by jingyu9575** [comment]
@jo-so the close event cannot be intercepted and suspended. The extension can respond to the event and send the jump command, but it will be processed after the default focus change.

**Comment by jingyu9575** [comment]
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated.

Please comment in #13 if there are issues with this feature.
