### ISSUE TITLE
SIMPLE QUESTION

### ISSUE THREAD

**Issue by Decopi** [jingyu9575/select-after-closing-current#12]
Hi,

First, thank you for your nice add-on.

Second, a simple question:
With this add-on, every time a tab is being closed, before going back to the selected tab (at add-on options), the tab on the right always is being silently loaded in the background (not focused). The add-on perfectly jumps to the right tab, but undesirably leaves the right tab always loading at background.

Please, what I need to do, how do I need to set the add-on options, in order to open my last active tab on tab closed, but without loading any other tabs?

Thank you in advance!

**Comment by jingyu9575** [comment]
This is an known issue of Firefox 57+ extension APIs, and extensions cannot prevent it. See #9, #10 for the details.

A Firefox contributor Ryan Hendrickson is currently [working](https://bugzilla.mozilla.org/show_bug.cgi?id=1500479) on improving the extension APIs. Hopefully, it will be completed in Firefox 65 (to be released on 2019-01-29), and then the problem can be fixed in the extension.

**Comment by Decopi** [comment]
> 
> 
> This is an known issue of Firefox 57+ extension APIs, and extensions cannot prevent it. See #9, #10 for the details.
> 
> A Firefox contributor Ryan Hendrickson is currently [working](https://bugzilla.mozilla.org/show_bug.cgi?id=1500479) on improving the extension APIs. Hopefully, it will be completed in Firefox 65 (to be released on 2019-01-29), and then the problem can be fixed in the extension.

OK, but just adding info, I am on Nightly 65, and the issue still exists.
I don't know if the possible Ryan's solution is related to 65 version, or to January 2019.

Thank you anyway for your useful add-on.

**Comment by jingyu9575** [comment]
Yes, it is still in progress. See this [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1500479), and when the status changed from "ASSIGNED" to "RESOLVED FIXED", it will be ready for the next day's Nightly.

**Comment by jingyu9575** [comment]
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated.

Please comment in #13 if there are issues with this feature.
