### ISSUE TITLE
Use new tab successors API in Firefox 65 to prevent default selection

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/select-after-closing-current#13]
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated. The issues #3, #9, #10, #11 and #12 are fixed.

Please comment here if there are issues with this feature.

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 ,

I am still testing, but at first sight it seems that "flashing" is not solved.

I am on FF' Nightly, FF' default dark theme, with ShadowFox and several dark theme Stylus' scripts.

The white-flashing doesn't happen at webpage first loading, but only when tab was closed and reopened.

If I disable SelectAfterClosing add-on... no more white flashing.

**Comment by jingyu9575** [comment]
@EstherMoellman Could you verify if your Firefox's version is 20181128100125 or later? The build number is in the 3rd cell in about:support.

I just tested and did not see white flash. When does this happen (e.g. opening tabs ... and then closing tabs ...)?

**Comment by jingyu9575** [comment]
@EstherMoellman I'm not sure what's happening. See the screen record for my test. I did not see white-flashing and the tab on the right was never activated. Besides, this extension does not change the reopen feature. If reopening causes flash, I think this can only be fixed in userChrome.css.

Is this happening all the time, or only if there is a white tab on the right? What if there is only two tabs and both of them are dark (like about:newtab or [the Nightly download website](https://www.mozilla.org/en-US/firefox/nightly/all/))?

@rayman89 The behavior is fixed. See the screen record. There is a custom userChrome.css rule that shows discarded tab in italic. It is shown that the 3rd tab is never activated.

It is not by intercepting, but preloading the next tab before closing. See [this explanation](https://github.com/jingyu9575/select-after-closing-current/issues/11#issuecomment-415407228) (Ryan's implementation is similar).

![test](https://user-images.githubusercontent.com/8923139/49302294-ab268180-f501-11e8-8d43-aead9d79ff75.gif)

The recorder failed to capture the context menu; it is using the "undo close tab" action.

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 , at your screen record is clear that you are using only FF' internal pages. In my opinion, this is the reason you are not going to see white-flashing. The right way to reproduce the flashing is:

1) Install Stylus, and install an universal dark theme, for example: https://userstyles.org/styles/164292/pure-darkness 

2) Open several webpages (let's say around 5), not FF' internal pages, normal webpages.

3) Close one by one.

4) Go to tab context, and click "Undo Close Tab".

If you have SelectAfterClosingCurrent (SACC) enable, the you will see the white-flashing while each webpage is reopened.

Repeat same procedure with SACC disable... you are not going to see white-flashing.

I can't tell you if this is happening with all FF. But is happening with my configuration:

Nightly 20181130093534
SACC 4.0b2
Stylus with several dark themes
UserChrome with ShadowFox + several modes

PS: Shadowfox is built to prevent white-flashing of regular webpages. The same goes to the universal dark theme. Both are pretty good restraining white-flashing. It is very difficult to see white-flashing with these CSS' scripts. So, if white-flashes are happening only when SACC is enable, then it most be a bug with the capability of interfere with userChrome and Stylus.

**Comment by jingyu9575** [comment]
I've tried again but am still unable to reproduce the issue. One thing to note is that ShadowFox's background color is slightly lighter than pure-darkness, and when a page is reopened, ShadowFox's background shows first, giving an impression of "light gray flash". This happens whether I enable this extension or not.

I'm suspecting that this extension is slowing down the tab creating process so the flash above is longer. I'll try to test it.

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 ,

I tested without ShadowFox (I removed completely from both, userChrome and userContent), and the white-flash is there, and it is only when SACC is enabled.

Just remembering, I can see the white-flash only when I close a tab, and reopen it through TabContext => Undo Close Tab. The white-flash is not grey, is 100% white, it is not happening at every reopened tab, but at least it happens in 50% of reopened tabs, and usually takes from 0,5 to 2 second (long flash). The main point is that the flash disappears when SACC is disabled. I can make a video for you, but believe me, you are going to see exactly what I am explaining to you here.

My opinion is that this white-flash is a minor issue, doesn't hurt, neither bothers a lot. However, this white-flash should see as a symptom of something else. As you said, perhaps something in your code is delaying the tab reopening, causing the white-flash.

I would like to stress that in general, your add-on is very nice. The main FF' bug was solved (tab on the right unexpectedly reloaded when an active tab on the left was opened), Also, your add-on is lightweight. So, once again, thank you for your effort!

**Comment by jingyu9575** [comment]
> it is only when SACC is enabled
> the flash disappears when SACC is disabled

I agree this is a bug of my extension, whatever the reason is. The difficult task is to find out the reason, and fix it or report it to Firefox. Unfortunately, I do not have any progress yet. 

I'll try to artificially increase the extension's work on tab creation, and see what happens.
