### ISSUE TITLE
[建议] 识别和跳转到同级子标签页

### ISSUE THREAD

**Issue by yfdyh000** [jingyu9575/select-after-closing-current#2]
上一个（左侧）或下一个（右侧）子标签页，允许配置。
未读（上次(标题/网址)变更以来未曾访问）的子标签页，tab utilities有此选项。用[激活](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onActivated)和[更新](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onUpdated)判别。

**Comment by jingyu9575** [comment]
看起来用 tabs.onUpdated: status === 'complete' 判断未读标签页更符合浏览器的设定（.tabbrowser-tab[unread]）。
