### ISSUE TITLE
Limiting a rule to adjacent tabs

### ISSUE THREAD

**Issue by PeterMinin** [jingyu9575/select-after-closing-current#20]
I think it would be useful to limit some rules to adjacent tabs only. That is, switch to the parent or a sibling tab, but only if that tab was right next to the current one (on the left or right), otherwise skip this rule.

My most common use case where I miss this feature is like this:
From my mailbox tab, I open a link to a certain website and move it next to other tabs from the same site, use it and then close it. If a "go to parent tab" rule works in this case, it switches me to the mailbox tab.

**Comment by jingyu9575** [comment]
Added in v5.
