### ISSUE TITLE
"Add" not working

### ISSUE THREAD

**Issue by hurzl** [jingyu9575/select-after-closing-current#31]
In the settings, the "+ Add" Button is greyed out, so I get not function at all.

firefox 101.0.1 (64-Bit)

**Comment by jingyu9575** [comment]
It works on my Firefox 101.0.1 on Windows. Maybe uninstall and install again?

**Comment by hurzl** [comment]
Didn't help. Also there are no default actions defined. Possible reason?

**Comment by jingyu9575** [comment]
In this URL *about:debugging#/runtime/this-firefox*, there is the *inspect* button for the extension. Maybe the error message is shown in the console.

**Comment by hurzl** [comment]
that opens _about:devtools-toolbox?id=select-after-closing-current%40qw.linux-2g64.local&type=extension_
which is completely empty ;(
(now firefox 102)

**Comment by hurzl** [comment]
New firefox profile, problem gone ...

**Comment by jingyu9575** [comment]
Glad to hear. I remember I also got some profile problem recently (fixed by manually clearing the storage in profile directory).
