### ISSUE TITLE
Shortcut support for different closing modes?

### ISSUE THREAD

**Issue by zoidbergthepopularone** [jingyu9575/select-after-closing-current#6]
Hi!

Is there any chance you could add a support for shortcuts for using a different close mode? E.g. I would press CTRL+ALT+1 to close current tab and select the left tab, or CTRL+ALT+2 to close current tab and select the right tab.

Thanks,.

**Comment by jingyu9575** [comment]
This looks like a simple feature, but currently extensions' shortcuts must be statically defined. It means that the key combinations have to be written (hardcoded) into the extension source, and cannot be changed unless I upload a new version. It seems that this feature needs many key combinations (`CTRL+ALT+1`, `CTRL+ALT+2`, `CTRL+ALT+3`), and if I write all of them in the extension, I think it is very likely to conflict with other extensions that use one of them, and cause problems with other users.
There is some [recent work](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) in Firefox's bug tracker. Let's see how it goes and if it can be used to implement this feature cleanly.

**Comment by zoidbergthepopularone** [comment]
Thanks for the answer.

I have two possible suggestions for implementation until the time Firefox supports shortcuts in a cleaner manner:

1) Use so complex shortcuts that they can't possibly interfere with anything (CTRL+ALT+SHIFT+letter). Once a shortcut is available, it can be changed to something sane using e.g. AuthHotKey or similar tool.

2) Only define two shortcuts and provide the option to choose which of the closing actions would occur. In fact, a single shortcut would suffice - we would have a regular close (without explicit shortcuts, instead depending on the system's default shortcut such as CTRL+F4) with a definable action (pretty much how it is done now), and an "alternative close" with a fixed shortcut (e.g. CTRL+ALT+F4) and another definable action.

Or both of these at the same time ;-)

**Comment by jingyu9575** [comment]
One shortcut Ctrl+Shift+F4 is added to 2.1b2 (beta channel). Ctrl+Alt is [not supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1364784). 

If this works for you, I think it is better not to define more shortcuts until Firefox's situation is improved. Even if only 9 extensions randomly pick shortcuts from Ctrl+Shift+[A-Z, 0-9, F1-F12], the probability of conflict is [more than 50%](https://en.wikipedia.org/wiki/Birthday_problem).

**Comment by zoidbergthepopularone** [comment]
Great! Thanks! I will try it out as soon as I figure out how to install beta versions of extensions.

**Comment by jingyu9575** [comment]
Firefox 60 added dynamic shortcut support. Now up to 5 shortcuts can be configured in this extension (version 3.0 on Firefox 60+). Ctrl+Alt is still not supported but there is some recent work.

**Comment by zoidbergthepopularone** [comment]
This is so awesome! Thanks!!

**Comment by zoidbergthepopularone** [comment]
Too bad I can't find a donate button, I would like to show my appreciation.

**Comment by jingyu9575** [comment]
I'm glad that you like my work. 
As I live in a country with a different set of popular online payment systems, setting up donations is difficult for me. Thank you!
