### ISSUE TITLE
Conflict with TreeStyleTab

### ISSUE THREAD

**Issue by kaz4ikeda** [jingyu9575/select-after-closing-current#7]
I have only one setting of focusing to left tab after closing the current tab.
I also use the addon "Tree Style Tab".
If I create a new tab next to a child tab, the focus-to-left setting doesn't work.
Phenomenon (A,B,C,D are tabs and numers touched to them are hierarchical levels):
Present: A1 B2 C1(new, focus) D1 -> A1 B2 D1(focus)
Intended: -> A1 B2(focus) D1

Thank you.

Sorry, the behavior is not restricted to the situation above. It seems to be always that the focusing is moved to a right tab.

**Comment by jingyu9575** [comment]
I cannot reproduce the problem on Firefox Developer 59.0b9/Linux and Firefox 58.0.2/Windows. Both extensions are the latest stable versions.

However, I think the following option in Tree Style Tab may be related to the conflict. Please change it to 2 and see if it works.
```
When the current tab is closed as a last child
    1. Focus to the previous tab in the tree
    2. Focus to the next tab always (Firefox's default)
```

**Comment by kaz4ikeda** [comment]
After confirming my present problem, I tried your suggestion 2.
Great! The SACC response come back.
My setting of the same behavior in separate addons was fault.
Thank you again.
