### ISSUE TITLE
Tab discard compatibility

### ISSUE THREAD

**Issue by trynomai** [jingyu9575/select-after-closing-current#9]
If the default tab to be selected is discarded - it's being loaded again. Maybe replacing onActivated with onRemoved will solve.

**Comment by jingyu9575** [comment]
I can confirm this behavior, but unfortunately I do not know how to solve this. Firefox 57+ compatible extensions cannot access Firefox's internal working, so the browser's default selection cannot be prevented. This extension already sends the selection request on `tabs.onRemoved`, but the default selection still happens first.

There are some recent discussions on the Firefox bug tracker about enhancing the tabs API, such as [Bug 1422509](https://bugzilla.mozilla.org/show_bug.cgi?id=1422509) and [1419947](https://bugzilla.mozilla.org/show_bug.cgi?id=1419947). However, there is little progress as far as I know.

**Comment by trynomai** [comment]
Since there is little progress, how about writing a workaround? It should be possible to select other tab before closing current. This requires a custom shortcut (it should be customizable). Also its possible to intercept middle clicks/clicks on tab close crosses in Tree Style Tab addon.

**Comment by jingyu9575** [comment]
I think intercepting the event in Tree Style Tab is not possible. From the link above, the event `try-move-focus-from-closing-current-tab` can only prevent Tree Style Tab from doing its own selection. The closing cannot be canceled (so the default selection cannot either).

I'll try with the shortcut approach.

**Comment by jingyu9575** [comment]
Version 3.0 has added (up to) 5 configurable shortcuts. It is only supported on [Firefox 60 or above](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update#Browser_compatibility). Note that Ctrl+Alt is currently [not supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1364784), and overriding built-in shortcuts such as Ctrl+W [may not work](https://bugzilla.mozilla.org/show_bug.cgi?id=1325692).

Some testing shows that intercepting Tree Style Tab is not possible. The extension can receive the event of clicking the close box, but cannot prevent the default behavior.

**Comment by jingyu9575** [comment]
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated.

Please comment in #13 if there are issues with this feature.
